import { buildSrcSet, fallbackSrc } from '../utils/images'

// Renders WebP with a JPEG fallback, both with srcset/sizes, for an image
// generated by scripts/optimize-images.mjs. `name` is the base filename
// (e.g. "portrait" for portrait-400.webp / portrait-400.jpg / ...).
export default function ResponsiveImage({ name, alt, sizes, className, loading }) {
  return (
    <picture className="contents">
      <source type="image/webp" srcSet={buildSrcSet(name, 'webp')} sizes={sizes} />
      <img
        src={fallbackSrc(name)}
        srcSet={buildSrcSet(name, 'jpg')}
        sizes={sizes}
        alt={alt}
        loading={loading}
        className={className}
      />
    </picture>
  )
}
