// Widths generated by scripts/optimize-images.mjs — keep in sync if you
// change the widths in that script.
export const IMAGE_WIDTHS = [400, 700, 1024]

export function buildSrcSet(name, ext) {
  return IMAGE_WIDTHS.map((w) => `/images/${name}-${w}.${ext} ${w}w`).join(', ')
}

export function fallbackSrc(name) {
  const largest = IMAGE_WIDTHS[IMAGE_WIDTHS.length - 1]
  return `/images/${name}-${largest}.jpg`
}
